{
  "comments": [
    {
      "key": {
        "uuid": "a6393e27_faeb3bfa",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 249,
      "author": {
        "id": 5867
      },
      "writtenOn": "2018-06-14T07:06:11Z",
      "side": 1,
      "message": "this catch (ReadFailedException e) { throw new IllegalArgumentException( is a little bit weird; you don\u0027t want to / can\u0027t easily just \"throws ReadFailedException\" to progagate and let e.g. FutureRpcResults catch and deal with it?  Or is it time we introduce a ReadFailedRuntimeException... Tom/Stephen, thoughts?",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "873e0162_b52b3426",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 249,
      "author": {
        "id": 5867
      },
      "writtenOn": "2018-06-14T07:12:38Z",
      "side": 1,
      "message": "let\u0027s continue to discuss this on the genius-dev list: https://lists.opendaylight.org/pipermail/genius-dev/2018-June/003045.html",
      "parentUuid": "a6393e27_faeb3bfa",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "80b67a78_c8cac605",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 249,
      "author": {
        "id": 1842
      },
      "writtenOn": "2018-06-14T11:32:06Z",
      "side": 1,
      "message": "I don\u0027t think IAE is appropriate here - IAE is typically for invalid user input but this is an internal failure. Also the method signature already provides us a way to propagate exceptions, ie a failed ListenableFuture so let\u0027s use that.",
      "parentUuid": "a6393e27_faeb3bfa",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9dac0409_5a984f0b",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 249,
      "author": {
        "id": 5867
      },
      "writtenOn": "2018-06-14T14:34:52Z",
      "side": 1,
      "message": "duh, yes right so that you really want to do here Faseela is:\n\n   return Futures.immediateFailedFuture(e);\n\nTom, in an ideal world the Cache should (also) have an async API...",
      "parentUuid": "80b67a78_c8cac605",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "d912b8ba_c94f5c99",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 249,
      "author": {
        "id": 817
      },
      "writtenOn": "2018-06-17T17:57:35Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "9dac0409_5a984f0b",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "89a400bf_b444efaa",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 255,
      "author": {
        "id": 1842
      },
      "writtenOn": "2018-06-14T11:32:06Z",
      "side": 1,
      "message": "Same here.",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "294ed54d_363db8b5",
        "filename": "interfacemanager/interfacemanager-impl/src/main/java/org/opendaylight/genius/interfacemanager/rpcservice/InterfaceManagerServiceImpl.java",
        "patchSetId": 1
      },
      "lineNbr": 255,
      "author": {
        "id": 817
      },
      "writtenOn": "2018-06-17T17:57:35Z",
      "side": 1,
      "message": "This is an existing exception type which has been used in conjunction with FutureRpcResults, (I think almost all RPCs in this class were migrated to use it this way.). FutureRpcResults is catching this exception, and then logging proper ERROR, and doing a return of the RPC failure. Do we have to change this whole approach as part of this fix?",
      "parentUuid": "89a400bf_b444efaa",
      "revId": "841da6a4072262e3c0d8fdaa98d085995103f90e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    }
  ]
}